### PR TITLE
Always print ancestor namespaces

### PR DESCRIPTION
**Pull request by achern**
If a user has permissions for a namespace but not its ancestors, the menu can be confusing with the ancestors left out.  For example, for this namespace structure:

- Restaurant Reviews
  - United States
  - Canada
- Hotel Reviews
  - United States
  - Canada

If the user is only authorized to edit pages in the United States sections, then the menu will show up as:

  - United States
  - United States

This change makes it so the ancestor namespaces are printed, but grayed out and unselectable.

### CODE REVIEW

**Comment by TorMec** [comment]
I'm a little bit reluctant to show "private" namespaces but I think that your idea is good.

So, an alternative could be to improve the drop-down menu adding a folder icon on the left and, for those for which the user is not allowed, only show the folder icon (maybe with a lock or something similar).

What do  you think?

**Comment by achern** [comment]
I don't think we need to worry about showing private namespaces, because DokuWiki itself doesn't make an effort to hide them.  So if the user sets up the wiki in this way, we can assume that they are okay with the private ancestor namespaces being known, as there are several places where they will be visible:

* When creating a new page, the full page path will be shown in the upper right corner (of the default theme).
* When viewing a page, the full path will be in the URL
* If hierarchical breadcrumbs are turned on, the full page path will be shown in the trace section

**Comment by TorMec** [comment]
Yep, I've made some test and you are absolutely right.

BTW the solution is to properly set the sneaky_index option in Configuration Manager (->https://www.dokuwiki.org/config:sneaky_index).

So, forget my previous comment and thanks for your precise definition!

**Comment by samwilson** [comment]
Thanks for this! :) Looks good.

**Pull request merged**
